name: Workday Job getter

on:
  schedule:
    
    - cron: '0 */4 * * *'
  workflow_dispatch: 

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 75 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python workday_jobs.py